config/routes.rb
Rails.application.routes.draw do
  get 'pins/index'

  get 'pins/new'

  get 'sessions/new'

  get 'users/new'

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'user_profile' => 'users#profile', :as => 'user_profile'

  root :to => 'pins#index'

  resources :users
  resources :sessions
  resources :pins do
    resources :comments
    member do
      put "like", to: "pins#upvote"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: { large: "500X500>", medium: "300x300!", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :pins
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_attached_file :image, styles: { large: "600X600>", medium: "300x300#", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, self.password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   def create
     @pin = Pin.find(params[:pin_id])
     @comment = @pin.comments.create(params[:comment].permit(:name, :body))

     redirect_to pin_path(@pin)
   end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]


  def index

    @pins = Pin.all
    @searchkey = ""
    if params[:q] != nil
      @searchkey = params[:q]
      @pins = Pin.where('lower(title) LIKE ?',  '%' + @searchkey.downcase + '%')
  end
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_index_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to user_profile_path(:id => user.id), :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params[:user].permit(:first_name, :last_name, :image, :birthday))
      redirect_to user_profile_path(:id => @user.id), :notice => "Your profile has been successfully updated!"
    else
      render 'edit'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up"
    else
      render "new"
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :image, :birthday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="media">
  <a class="pull-left" href="#">
    <img class="media-object" src="" alt="">
  </a>
  <div class="media-body">
    <h4 class="media-heading"><%= comment.name %> <small><%= time_ago_in_words(comment.created_at) %> ago</small></h4>

    <h4><%= comment.body %></h4>
  </div>
  <% if current_user %>
      <p><%= link_to 'Delete', [comment.pin, comment],
                     method: :delete,
                     class: "btn btn-primary btn-small",
                     data: { confirm: 'Are you sure?' } %>

      </p>

  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for [@pin, @pin.comments.build] do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, value: current_user.first_name + " " + current_user.last_name, disabled: true, class: "form-control" %>
    </p>

    <p>

      <%= f.text_area :body, class: "form-control"%>
    </p>
    <br/>
    <p>
      <%= f.submit "Submit", class: "btn btn-success" %>
    </p>

<% end %>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Profile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Pinboard', root_path, class: "navbar-brand" %>
        </div>

        <div>
          <div class="col-sm-6 col-md-6">
            <form class="navbar-form" role="search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="q" size="100">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
              </div>
            </form>
          </div>
          <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <li><%= link_to 'Sign up', new_user_path %></li>
                  <li><%= link_to 'Sign in', log_in_path %></li>
            <% end %>
            </ul>

          <% if current_user %>
            <ul class="nav navbar-nav">
              <li><%= link_to "All Pin", pins_index_path %></li>
              <li><%= link_to 'New Pin', new_pin_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to 'Hi, ' + current_user.email, edit_user_path(current_user) %> </li>
                  <li><%= link_to 'Sign out', log_out_path %></li>
            </ul>
          <% end %>
        </div>


      </div>
    </nav>

    <div  class="container">
          <% flash.each do |name, msg| %>
            <% if flash[:notice] %>
              <div id="notice_wrapper" class="alert alert-success">
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
            <% else %>
              <div id="notice_wrapper" class="alert alert-danger">
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
            <% end %>

          <% end %>

        <%= yield %>
    </div>


    <script>
      $(document).ready(function(){
         setTimeout(function(){
            $('#notice_wrapper').fadeOut("slow", function(){
                $(this).remove();
            })
         }, 4500);
      });
    </script>

</body>
</html>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    #errors
      %h2
        = pluralize(@pin.errors.count, "error")
        prevented this Pin from saving
        %ul
          - @pin.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  .form-group
    = f.input :title, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: 'btn btn-primary'

app/views/pins/edit.html.haml
%h1 Edit Pin

=render 'form'
= link_to "Cancel", pins_index_path

app/views/pins/index.html.haml
.board_content
  #pins.transitions-enabled.infinite-scroll

    - @pins.each do |pin|
      .box.panel.panel-default
        = link_to (image_tag pin.image.url(:medium)), pin
        .panel-body
          %h3= link_to pin.title, pin
          %p.user
          Submitted by
          = pin.user.email

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Pin
  =render 'form'
  = link_to 'Back', @pin

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        %p= link_to( image_tag(@pin.image.url(:medium)) , @pin.image.url, :data => { :colorbox => true, :width => '500px', :colorbox_width => '70%', :colorbox_height => '70%' } )
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
        %p
        Submitted by
        = @pin.user.email
      .panel-footer
        .row
          .col-md-6
            %h2= " #{@pin.comments.count} Comments"
            = render @pin.comments

          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @pin.get_upvotes.size
              - if current_user
                = link_to "Edit", edit_pin_path, class: "btn btn-default"
                = link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"





      <!-- Comments Form -->
      .well
        %h4 Leave a Comment
        = render "comments/form"

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <h1>Edit Profile</h1>
    <h2> <%= @user.email %></h2>
    <p><%= image_tag @user.image.url(:medium) %></p>


    <%= form_for @user, :html => { multipart: true, :class => 'form-signin'},  method: :patch do |f| %>
        <p>
          <%= f.label :image %><br />
          <%= f.file_field :image, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :first_name  %><br />
          <%= f.text_field :first_name, class: 'form-control', placeholder: "First name" %>
        </p>
        <p>
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, class: 'form-control', placeholder: "Last name" %>
        </p>
        <p>
          <%= f.label :birthday %><br />
          <div class="input-group date">
            <input type="text" class="form-control" id="birthday" placeholder="dd/mm/yyyy" name="user[birthday]" value="<%= @user.birthday %>" data-date-format="mm/dd/yyyy"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
          </div>
        </p>

        <div><%= f.submit class: 'btn btn-primary', value: 'Update' %></div>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h1>Sign Up</h1>

        <%= form_for @user, :html => { multipart: true, :class => 'form-signin'} do |f| %>
            <% if @user.errors.any? %>
                <div class="error_messages">
                  <h2>Form is invalid</h2>
                  <ul>
                    <% for message in @user.errors.full_messages %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <p>
              <%= f.label :email, class: 'sr-only' %><br />
              <%= f.text_field :email, class: 'form-control', placeholder: "Email address" %>
            </p>
            <p>
              <%= f.label :password , class: 'sr-only' %><br />
              <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
            </p>
            <p>
              <%= f.label :password_confirmation, class: 'sr-only' %><br />
              <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Retype Password" %>
            </p>

          <p>
            <%= f.label :image, class: 'sr-only' %><br />
            <%= f.file_field :image, class: 'form-control' %>
          </p>


            <div><%= f.submit class: 'btn btn-primary', value: 'Sign Up' %></div>
        <% end %>
    </div>
    <div class="col-md-4"></div>
</div>

app/views/users/profile.html.erb
<div class="col-md-6 col-md-offset-3">
    <h1>User Profile Page</h1>
    <p><%= image_tag @user.image.url(:medium) %></p>
    <p>Welcome, <%= @user.email %></p>
    <h2>Bio</h2>
    <p>First Name: <%= @user.first_name %></p>
    <p>Last Name: <%= @user.last_name %></p>
    <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p>
</div>